services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_API
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-scripts/init:/docker-entrypoint-initdb.d/

  node_app:
    build:
      context: . # El contexto de construcción es la raíz del proyecto
      dockerfile: ./Dockerfile # Ruta al directorio que contiene el Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
