services: 
  postgres:
    image: postgres:latest
    container_name: postgres_container_API
    ports:
      - "5434:5432"
    environment: 
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: zytologue_API
    
