services: 
  postgres:
    image: postgres:latest
    container_name: postgres_container_API
    ports:
      - "${PORT}:5432"
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    
